In [1]:
import numpy as np
import pandas as pd

In [34]:
X = np.random.randn(100, 200)

X.shape

(100, 200)

In [54]:
y = np.random.randint(0, 10, size=(100,))

In [55]:
y

array([7, 2, 7, 5, 1, 1, 4, 3, 3, 5, 5, 4, 4, 5, 8, 2, 9, 4, 6, 8, 2, 9,
       8, 0, 1, 3, 3, 3, 8, 5, 7, 8, 1, 3, 7, 6, 6, 4, 9, 9, 6, 2, 4, 4,
       4, 7, 2, 3, 0, 0, 9, 2, 7, 6, 9, 7, 8, 5, 5, 9, 9, 9, 8, 9, 0, 5,
       9, 3, 4, 5, 4, 3, 3, 7, 6, 1, 7, 5, 1, 5, 6, 5, 6, 0, 9, 1, 7, 4,
       1, 3, 9, 2, 2, 4, 8, 0, 4, 7, 7, 1])

In [56]:
Y = np.zeros((100, 10))

In [57]:
Y.shape

(100, 10)

In [58]:
Y[np.arange(100), y] = 1

In [59]:
Y

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 

In [82]:
W1 = np.random.randn(20, 200)
b1 = np.random.randn(20, 1)
W2 = np.random.randn(10, 20)
b2 = np.random.randn(10, 1)
W1.shape
W2.shape

# first 200 input size so 20x200 then 20 neurons to pass through 10 neurons so 10x20

(10, 20)

In [83]:
def sm(z): # ex / sum(ex0), we have to pass the whole vector through this function so that we can do the summation below
    e_z = np.exp(z - np.max(z))
    return e_z / np.sum(e_z, axis=0, keepdims=True)


In [84]:
def fwd(X): # forward propagation
    z1 = np.dot(W1, X.T) + b1
    a1 = np.tanh(z1)
    z2 = np.dot(W2, a1) + b2
    y = sm(z2)
    return y

In [63]:
y_hat = fwd(X)

In [64]:
m = 100

loss = -np.sum(Y.T*np.log(y_hat + 1e-8))/m

print("Loss = ", loss)

Loss =  7.80937573258989


In [85]:
y_hat

array([[5.31235847e-01, 7.02284245e-02, 3.86009573e-04, 8.53770269e-04,
        4.44046175e-01, 1.89529495e-04, 7.88710108e-03, 1.02167612e-03,
        1.26394795e-06, 2.01675077e-03, 2.23505261e-02, 3.73535557e-01,
        8.62850370e-01, 6.93432399e-02, 6.95200325e-01, 3.69135181e-03,
        4.87958624e-05, 3.75681552e-04, 3.00620112e-01, 1.92124287e-01,
        4.07516513e-04, 9.28775770e-04, 1.43888729e-02, 1.70239013e-05,
        3.30017827e-01, 4.69485844e-04, 1.07202274e-03, 4.22803133e-02,
        1.04471717e-05, 3.45718451e-01, 3.15962969e-02, 8.66453710e-03,
        4.88413619e-02, 8.85705815e-01, 1.11474734e-04, 1.39455161e-02,
        8.13958704e-04, 5.89208607e-03, 2.57731194e-02, 1.10582127e-04,
        7.62923735e-05, 3.56104870e-04, 8.70150658e-02, 1.35345277e-01,
        3.56195840e-05, 8.04392595e-01, 1.64363813e-02, 7.35362352e-04,
        6.19501099e-05, 9.49162565e-02, 2.15183115e-03, 3.16677365e-04,
        2.06767554e-04, 1.72757023e-05, 6.01575584e-02, 3.498940

In [65]:
y_pred = np.argmax(y_hat, axis=0)
y_pred

array([0, 3, 9, 2, 0, 6, 7, 7, 9, 6, 4, 8, 0, 2, 0, 8, 7, 7, 2, 1, 5, 6,
       7, 8, 9, 2, 8, 4, 9, 1, 1, 7, 1, 0, 2, 9, 1, 6, 2, 9, 8, 6, 3, 9,
       7, 0, 7, 9, 9, 1, 3, 5, 2, 8, 9, 3, 9, 9, 1, 5, 2, 0, 9, 8, 7, 2,
       8, 9, 2, 8, 9, 7, 2, 2, 7, 3, 9, 1, 5, 1, 6, 9, 9, 9, 0, 9, 8, 5,
       0, 8, 9, 2, 9, 7, 7, 1, 5, 9, 6, 7], dtype=int64)

In [66]:
y_pred

array([0, 3, 9, 2, 0, 6, 7, 7, 9, 6, 4, 8, 0, 2, 0, 8, 7, 7, 2, 1, 5, 6,
       7, 8, 9, 2, 8, 4, 9, 1, 1, 7, 1, 0, 2, 9, 1, 6, 2, 9, 8, 6, 3, 9,
       7, 0, 7, 9, 9, 1, 3, 5, 2, 8, 9, 3, 9, 9, 1, 5, 2, 0, 9, 8, 7, 2,
       8, 9, 2, 8, 9, 7, 2, 2, 7, 3, 9, 1, 5, 1, 6, 9, 9, 9, 0, 9, 8, 5,
       0, 8, 9, 2, 9, 7, 7, 1, 5, 9, 6, 7], dtype=int64)

In [67]:
y

array([7, 2, 7, 5, 1, 1, 4, 3, 3, 5, 5, 4, 4, 5, 8, 2, 9, 4, 6, 8, 2, 9,
       8, 0, 1, 3, 3, 3, 8, 5, 7, 8, 1, 3, 7, 6, 6, 4, 9, 9, 6, 2, 4, 4,
       4, 7, 2, 3, 0, 0, 9, 2, 7, 6, 9, 7, 8, 5, 5, 9, 9, 9, 8, 9, 0, 5,
       9, 3, 4, 5, 4, 3, 3, 7, 6, 1, 7, 5, 1, 5, 6, 5, 6, 0, 9, 1, 7, 4,
       1, 3, 9, 2, 2, 4, 8, 0, 4, 7, 7, 1])

In [72]:
confusion_matrix = np.zeros((10, 10), dtype=int)

for i in range(len(y)):
    confusion_matrix[y[i]][y_pred[i]] += 1

confusion_matrix

array([[0, 2, 0, 0, 0, 0, 0, 1, 1, 2],
       [2, 1, 0, 1, 0, 1, 1, 1, 0, 2],
       [0, 0, 1, 1, 0, 2, 1, 1, 1, 1],
       [1, 0, 2, 0, 1, 0, 0, 2, 2, 3],
       [1, 0, 1, 1, 0, 2, 1, 4, 1, 2],
       [0, 4, 3, 0, 1, 0, 1, 0, 1, 2],
       [0, 1, 1, 0, 0, 0, 1, 1, 2, 2],
       [2, 1, 3, 1, 0, 0, 1, 0, 1, 3],
       [1, 1, 0, 0, 0, 0, 0, 3, 0, 3],
       [2, 0, 2, 1, 0, 1, 1, 1, 2, 3]])

In [73]:
acc = np.trace(confusion_matrix) / np.sum(confusion_matrix)

In [74]:
acc

0.06

In [77]:
prec = []
recall = []
f1 = []

for i in range(10):
    tp = confusion_matrix[i][i]
    fp = np.sum(confusion_matrix[:, i]) - tp
    fn = np.sum(confusion_matrix[i, :]) - tp

    p = tp/(tp+fp)
    r = tp/(tp+fn)
    f = 2*p*r / (p+r+1e-8)

    prec.append(p)

    f1.append(f)
    recall.append(r)

In [78]:
p_value = np.mean(prec)
r_value = np.mean(recall)
f_value = np.mean(f1)

In [79]:
p_value

0.045021500238891544

In [80]:
r_value

0.059188034188034186

In [81]:
f_value

0.05005012338381547