In [1]:
import numpy as np

In [5]:
def PCA(X, k):
    X_mean = np.mean(X, axis = 0)
    X_centered = X - X_mean

    covm = np.cov(X_centered, rowvar=False)
    eva, evec = np.linalg.eig(covm)

    sort_idx = np.argsort(eva)[::-1]

    evec = evec[:, sort_idx]
    eva = eva[sort_idx]

    pc = evec[:, :k]

    X_reduced = np.dot(X_centered, pc)

    return X_reduced, pc, evec[:k]

In [6]:
X = np.random.rand(100, 5)

In [7]:
X_reduced, components, eig_vals = PCA(X, 2)

In [8]:
X_reduced.shape

(100, 2)

In [9]:
X_reduced

array([[ 0.2065975 , -0.34027722],
       [-0.15727994,  0.19652265],
       [-0.34449115,  0.41240514],
       [ 0.29530726,  0.32851655],
       [-0.36540765, -0.40586499],
       [-0.22415622,  0.43019136],
       [ 0.03866   ,  0.11944082],
       [-0.34385639,  0.57083977],
       [-0.46388235, -0.2275046 ],
       [ 0.05232661,  0.29000873],
       [-0.06394589, -0.01620496],
       [-0.2884381 , -0.32833454],
       [ 0.15712223,  0.01713409],
       [-0.79685984, -0.13793729],
       [-0.32085057,  0.41054611],
       [-0.2699291 ,  0.39919722],
       [ 0.27602579,  0.26248815],
       [ 0.51871948,  0.28627925],
       [-0.32741732,  0.31887627],
       [ 0.25653915, -0.20756706],
       [-0.200434  , -0.41054306],
       [ 0.21493722, -0.17094143],
       [ 0.13306312,  0.28852739],
       [-0.0932374 ,  0.07093853],
       [ 0.08264234,  0.02299447],
       [-0.31752351, -0.50110909],
       [-0.12176405, -0.24017737],
       [-0.20230656,  0.47189354],
       [-0.34911091,

In [10]:
components

array([[ 0.37201661, -0.2058332 ],
       [ 0.5409861 , -0.32501341],
       [ 0.25706919,  0.92101225],
       [-0.61632515, -0.04735684],
       [ 0.35070845, -0.03863602]])

In [11]:
eig_vals

array([[ 0.37201661, -0.2058332 , -0.14350845, -0.76447749,  0.46283457],
       [ 0.5409861 , -0.32501341,  0.19382276,  0.59325893,  0.46062664]])