In [1]:
import numpy as np
import pandas as pd

In [8]:
def SVD(X, k):
    X_mean = np.mean(X, axis=0)
    X_centered = X - X_mean

    U, S, Vt = np.linalg.svd(X_centered, full_matrices=False)

    V_k = Vt[:k].T

    return U, S, Vt

In [9]:
X = np.random.rand(100,5)

X_reduced, components, singular_values = SVD(X, k=2)

print("Reduced Shape:", X_reduced.shape)
print("Principal Components:\n", components)
print("Top Singular Values:", singular_values)

Reduced Shape: (100, 5)
Principal Components:
 [3.27916329 3.0764002  2.81985146 2.79934816 2.60265443]
Top Singular Values: [[ 0.60180753  0.57679607 -0.07191973  0.47352976 -0.27519285]
 [-0.29761966  0.41648878  0.76617369  0.18563476  0.34128763]
 [ 0.56571096  0.18023735  0.10271422 -0.68234554  0.41393232]
 [ 0.15054646 -0.22688967 -0.28338688  0.49306916  0.77616462]
 [ 0.45448554 -0.6402179   0.56298054  0.18054547 -0.18444557]]
