In [1]:
import numpy as np
import pandas as pd

In [6]:
def SVD(X, k):
    X_mean = np.mean(X, axis=0)
    X_centered = X - X_mean

    U, S, Vt = np.linalg.svd(X_centered, full_matrices=False)

    V_k = Vt[:k].T

    return U, S, Vt

In [7]:
X = np.random.rand(100,5)

X_reduced, components, singular_values = SVD(X, k=2)

print("Reduced Shape:", X_reduced.shape)
print("Principal Components:\n", components)
print("Top Singular Values:", singular_values)

Reduced Shape: (100, 5)
Principal Components:
 [3.20819908 2.95427453 2.88911493 2.73722503 2.52301613]
Top Singular Values: [[-0.50095395 -0.33369214 -0.11717174  0.67930141 -0.40313158]
 [ 0.35322191 -0.55888084  0.55785895 -0.19270799 -0.46318842]
 [ 0.74205649  0.23915047 -0.06258163  0.6205494  -0.05622454]
 [ 0.24716737 -0.29853747 -0.81649738 -0.29125968 -0.313502  ]
 [ 0.11198157 -0.6557318  -0.06693095  0.1774809   0.72214729]]
