In [1]:
import numpy as np
import pandas as pd

In [19]:
def SVD(X, k):
    X_mean = np.mean(X, axis=0)
    X_centered = X - X_mean

    U, S, Vt = np.linalg.svd(X_centered, full_matrices=False)

    V_k = Vt[:k].T

    return U, S, Vt

In [20]:
X = np.random.rand(100,5)

U, S, Vt = SVD(X, k=2)



In [21]:
U

array([[-2.06157077e-01, -1.28657441e-02, -1.99724405e-02,
        -1.27708535e-03,  1.20305665e-01],
       [ 1.81253255e-01, -8.53008183e-02,  3.61524750e-02,
         1.15084948e-01, -8.00122489e-02],
       [-1.91039249e-01, -9.13850552e-02, -4.89026829e-02,
         1.09017953e-01, -2.60348902e-02],
       [ 1.57043633e-01,  5.43918130e-02, -1.67544690e-02,
         1.74792150e-02,  1.23500713e-01],
       [ 4.19779509e-02, -1.09592460e-01,  9.91762381e-02,
        -2.43709252e-01,  4.13708108e-02],
       [-8.93246192e-02,  1.62698940e-02,  1.69159360e-01,
         5.49150447e-02,  1.20324335e-01],
       [-4.88776040e-02, -6.15867187e-02,  5.02480620e-02,
        -1.04837859e-01,  1.67212823e-02],
       [ 1.67579368e-01, -2.77390042e-02, -1.45220603e-01,
         3.09186085e-02,  1.48695316e-01],
       [-6.99199621e-02, -7.52444705e-02,  1.90405578e-02,
        -1.46096679e-01, -7.10130044e-02],
       [-1.93144858e-02, -8.32164817e-02,  2.31124195e-01,
         1.04699244e-02

In [22]:
S

array([3.26164617, 2.88289187, 2.81488924, 2.54388518, 2.50200672])

In [23]:
Vt

array([[-0.15227192,  0.57873182,  0.58004416,  0.15925179,  0.52921676],
       [ 0.15223223, -0.26723963, -0.40197744,  0.63252299,  0.586291  ],
       [-0.7521616 , -0.28592615,  0.22229416,  0.4688933 , -0.28848493],
       [-0.02464157, -0.69590957,  0.4199232 , -0.40694007,  0.41613332],
       [ 0.62232173, -0.16615824,  0.52555944,  0.43484755, -0.34612424]])